{% set name = "napari-large-image-importer" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: bf14732e183f2a175a67d90c2e64b978c85f036705ef6caed5991d16a1aca284

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42.0.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - napari
    - magicgui
    - qtpy
    - tifffile
    - imagecodecs
    - zarr
    - dask-core
    - pyqt

test:
  imports:
    - napari_large_image_importer
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}
    - pyqt

about:
  home: https://github.com/hiroalchem/napari-large-image-importer
  summary: Napari plugin for easy, memory-efficient import of large images.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hiroalchem
